import nextConfig from 'eslint-config-next'

const eslintConfig = [
  ...nextConfig,
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'out/**',
      'build/**',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
    ],
  },
  {
    // components/ui/** and hooks/use-mobile.ts are vendored shadcn/ui
    // primitives (generated by the shadcn CLI), not hand-written app code.
    // The newer React 19 "purity" rules (set-state-in-effect, purity,
    // static-components) flag a few patterns in that generated code.
    // Upstream shadcn/ui code is regenerated via the CLI rather than
    // hand-patched, so these rules are relaxed here instead of drifting
    // from the generator's output.
    files: ['components/ui/**/*.{ts,tsx}', 'hooks/use-mobile.ts'],
    rules: {
      'react-hooks/set-state-in-effect': 'off',
      'react-hooks/purity': 'off',
      'react-hooks/static-components': 'off',
    },
  },
]

export default eslintConfig
